---
# tasks file for logstash
- name: Install apt-transport-https
  become: yes
  apt:
    name: apt-transport-https
    state: present

- name: Add an Apt signing key, uses whichever key is at the URL
  become: yes
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash repository.
  become: yes
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present

- name: Check if Logstash is already installed.
  stat: path=/etc/init.d/logstash
  register: logstash_installed

- name: Update apt cache if repository just added.
  become: yes
  apt: update_cache=yes
  when: not logstash_installed.stat.exists

- name: Install Logstash.
  become: yes
  apt:
    name: logstash
    state: present
